[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "ffmpeg-full"]

[phases.build]
cmds = [
    "python3 -m pip install --user yt-dlp",
    "npm install",
    "npm run build"
]

[start]
cmd = "npm start"
